version: "3.7"

services:
  opendata-api:
    container_name: opendata-api
    tty: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    image: opendata-api:3.0.0
    command: /bin/bash
    ports:
      - ${PORT}:3000
    volumes:
      - ./:/usr/app/:cached
    networks:
      - api-shared

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - api-shared

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.14
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bewai.com
      PGADMIN_DEFAULT_PASSWORD: bewai
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api-shared

  pghero:
    container_name: pghero
    image: ankane/pghero
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}"
    ports:
      - 3200:8080
    depends_on:
      - postgres
    networks:
      - api-shared
  # redis:
  #   container_name: redis
  #   hostname: redis
  #   image: redis:latest
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   volumes:
  #     - ./redis-data:/data
  #   command: >
  #     --requirepass ${REDIS_PASSWORD}
  #   networks:
  #     - api-shared

networks:
  api-shared:
    name: api-shared

volumes:
  postgresdata:
  pgadmin-data: # redis-data:
